version: "3.9"
   
services:
  web:
    build: .
    command: bash -c "sleep 2 && python manage.py migrate && python manage.py loaddata library.json && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - .:/db
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE 
